# Site settings
title: Pratik Deoolwadikar
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pratik Deoolwadikar
user_description:
user_title: Computer Engineer | Data Science, Android, Web & Code Fanatic
email: pratik.deoolwadikar@gmail.com
twitter_username: d_pDev
github_username:  fragmetal
facebook_username: pratik.deoolwadikar.7
gplus_username:  108161892064569391491
linkedin_username: pratikdeoolwadikar

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
